### ISSUE TITLE
Cropping Images

### ISSUE THREAD

**Issue by BB1464** [gadenbuie/garrickadenbuie-com#122]
Hi there @gadenbuie, I am trying to reproduce your latest blog post at my end here but I am stock, after reading in the image, I get the following error when I try to call the profile. Please can you help me to resolve this ? The line that is giving me issues is below in bold. I suspect after reading in the image with magick the image is corrupted because I cannot view them

```r
library(magick)
library(purrr)
dir.create("profiles")
photo_ids <- c("DItYlc26zVI", "bpxgyD4YYt4", "6anudmpILw4", "3dqSZidOkvs")

for (id in photo_ids) {
  download.file(
    sprintf("https://source.unsplash.com/%s", id),
    sprintf("profiles/%s.jpg", id)
  )
}

#I’ve put the photos in a profiles/ directory so that I can list the them all at once:  
fs::dir_ls("profiles")
## profiles/3dqSZidOkvs.jpg profiles/6anudmpILw4.jpg profiles/DItYlc26zVI.jpg 
## profiles/bpxgyD4YYt4.jpg
```

> # Magick with R
> 
> The first step is to use the magick package to read in our profile pictures.

```r
profiles <- 
  fs::dir_ls("profiles") |>
  map(image_read)

profiles # **This is the line that is giving me error**
```

```
Error in magick_image_info(image) : 
  rsession-utf8.exe: Invalid geometry argument
```

**Comment by BB1464** [comment]
**This is the output when I import magick**
library(magick)

Linking to ImageMagick 6.9.12.3
Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
Disabled features: fontconfig, x11

I am using magick version  **2.7.3**

**Comment by gadenbuie** [comment]
Very odd. Can you also share the output of

```r
fs::file_info(fs::dir_ls("profiles"))
```

That would help verify that the files downloaded correctly

**Comment by BB1464** [comment]
fs::file_info(fs::dir_ls('profiles'))

path   type    size permissions modification_time   user  group device_id
  <fs::path>    <fct> <fs::> <fs::perms> <dttm>              <chr> <chr>     <dbl>
1 …SZidOkvs.jpg   file  132.8K rw-        2022-07-13 17:15:36 NA    NA    347202984
2 …udmpILw4.jpg file   45.2K rw-         2022-07-13 17:15:31 NA    NA    347202984
3 …gyD4YYt4.jpg  file   78.7K rw-         2022-07-13 17:15:25 NA    NA    347202984
4 …Ylc26zVI.jpg   file     86.1K rw-        2022-07-13 17:15:17 NA    NA    347202984

**Comment by BB1464** [comment]
![image_2022-07-13_173308712](https://user-images.githubusercontent.com/76583394/178784940-f81fdcd7-c15a-4724-89b1-2c73da37ce65.png)

**Comment by gadenbuie** [comment]
I'm not sure how to help at this point. I think maybe you should open an issue in magick using the example above as a reprex. https://github.com/ropensci/magick
