### ISSUE TITLE
truncate param in Hyde theme

### ISSUE THREAD

**Issue by casualinference** [gadenbuie/garrickadenbuie-com#15]
Is there a parameter that can be used to set whether posts are truncated or not in the homepage using your modified Hyde theme?

**Comment by gadenbuie** [comment]
The short answer is no, only the post titles are shown on the homepage.

I have a fork of Hyde here -- https://github.com/gadenbuie/hyde -- that you can use. It doesn't include all of the tweaks I've made to my webpage, but the theme should work well with blogdown out of the box.

I'm not totally sure what you mean by "truncated" on the homepage, but I'm guessing that you're referring to how the theme only shows the title. You can see the hugo template for the homepage layout here https://github.com/gadenbuie/hyde/blob/master/layouts/index.html, or check out the [highly modified version](https://github.com/gadenbuie/garrickadenbuie-com/blob/master/layouts/index.html) is use in my blog as an example of how you can edit the layout to fit your needs.
