### ISSUE TITLE
add a license?

### ISSUE THREAD

**Issue by daviddalpiaz** [gadenbuie/garrickadenbuie-com#81]
Would you consider adding a license to this repo? I'm guessing that might be a lot to ask to put a blanket license for the entire website and all the code you post on it.

I'm wondering because I'd like to include your **excellent** `cal()` function in a personal R package. (https://www.garrickadenbuie.com/blog/r-console-calendar/) Or have you by chance included that code in a package somewhere with a license?

**Comment by daviddalpiaz** [comment]
Alternatively, any interest in starting a package around that function and idea? Something like `calendr`? (That doesn't exist right?) Just being able to type `cal()` and get that calendar at any moment is super useful, but long term I think it would be interesting to consider additional functionality to define specific calendars. For my use case, I very often need to reference the last page of this document: https://www.senate.illinois.edu/ep/Props/1415/FINAL/EP15.08final.pdf It would be super cool/useful to input that information then generate a calendar, something like `make_cal(cal = use_define_cal)`.

**Comment by gadenbuie** [comment]
Thanks for bringing this up and sorry for the delay in getting back to you. I should definitely add a note to the site about code licensing, but I'll have to think about how best to do that. In the mean time, please feel free to use the code from the calendar post under an MIT license. It was mostly taken/adapted from [ggweekly](https://github.com/gadenbuie/ggweekly), which is also MIT licensed.

I think a package would be great (I love packages!) but unfortunately I don't think I'll have time to contribute. But I'd love to see what you do so please drop a link here and I'll certainly check it out!

**Comment by gadenbuie** [comment]
I added an explicit license to my page in the last redesign

https://www.garrickadenbuie.com/colophon/#license
